#!/usr/bin/env python3
"""Generate the corpus input-composition report (BR-0).

The corpus is a *document extraction* benchmark, but most of its documents never
existed as a rendered page. This script classifies every document by the input
modality it actually reached the extractor through, so that accuracy claims can be
scoped honestly.

Usage:
    python3 scripts/composition_report.py            # print markdown to stdout
    python3 scripts/composition_report.py -o docs/composition.md
"""

from __future__ import annotations

import argparse
import collections
import json
import pathlib
import sys

# Input tiers, ordered from "most like a real document" to "least".
TIERS = [
    ("A1", "Image → OCR", "Scanned raster image decoded by an OCR engine."),
    ("A2", "PDF → parse", "PDF decoded by a layout-aware parse engine."),
    ("A3", "Office → parse", "xlsx/docx/pptx decoded by a parse engine."),
    (
        "B",
        "HTML → markdown",
        "Machine-readable HTML converted to markdown. No visual layout.",
    ),
    ("C", "Plain text", "Delivered as text. Never had a page."),
    ("D", "Authored markdown", "Synthesised directly as markdown. Never had a page."),
]
# Tiers that went through a parse engine at all, and the stricter "had a page" set.
PARSED = {"A1", "A2", "A3"}
RENDERED = {"A1", "A2"}


def classify(fmt):
    """Map a manifest's original_format onto an input tier."""
    f = (fmt or "MISSING").strip()
    if "JPEG" in f or "image" in f.lower():
        return "A1"
    if f.startswith("PDF"):
        return "A2"
    if f in ("xlsx", "docx", "pptx"):
        return "A3"
    if f.startswith("HTML"):
        return "B"
    if f in ("text", "MISSING", ""):
        return "C"
    return "D"


def is_synthetic(manifest):
    src = manifest.get("source_name") or ""
    return ("ynthetic" in src) or ("Hand-crafted" in src) or src.startswith("FieldBench ")


def load(root: pathlib.Path):
    rows = []
    for path in sorted(root.glob("*/manifests/*.json")):
        try:
            m = json.loads(path.read_text())
        except json.JSONDecodeError as e:
            print(f"warning: unreadable manifest {path}: {e}", file=sys.stderr)
            continue
        rows.append(
            {
                "category": path.parts[-3],
                "tier": classify(m.get("original_format")),
                "provenance": "synthetic" if is_synthetic(m) else "real",
            }
        )
    return rows


def pct(n, d):
    return f"{(n / d * 100):.1f}%" if d else "—"


def render(rows) -> str:
    n = len(rows)
    if not n:
        return "No manifests found.\n"
    out = []
    w = out.append

    by_tier = collections.Counter(r["tier"] for r in rows)
    by_tier_prov = collections.Counter((r["tier"], r["provenance"]) for r in rows)
    rendered = sum(by_tier[t] for t in RENDERED)
    parsed = sum(by_tier[t] for t in PARSED)
    never = n - parsed - by_tier["B"]
    real = sum(1 for r in rows if r["provenance"] == "real")
    real_rendered = sum(
        1 for r in rows if r["provenance"] == "real" and r["tier"] in RENDERED
    )

    w("<!-- GENERATED by scripts/composition_report.py — do not edit by hand. -->")
    w("# Corpus input composition\n")
    w(
        "This corpus is used as a **document extraction** benchmark. Most of its documents "
        "never existed as a rendered page. This table records what each document actually "
        "was when it reached the extractor, so accuracy numbers can be read correctly.\n"
    )

    w("## Headline\n")
    w(
        f"- **{rendered} of {n} documents ({pct(rendered, n)}) came from a rendered page** (image or PDF)."
    )
    w(
        f"- {parsed} ({pct(parsed, n)}) went through a parse engine at all, counting office formats."
    )
    w(
        f"- {by_tier['B']} ({pct(by_tier['B'], n)}) are machine-readable HTML converted to markdown."
    )
    w(
        f"- **{never} ({pct(never, n)}) never had a page at all** — plain text or authored markdown."
    )
    w(
        f"- Of the {real} documents labelled *real*, only **{real_rendered} "
        f"({pct(real_rendered, real)}) came from a rendered page**. The rest are clean "
        "HTML or plain text.\n"
    )
    w(
        "> **Scope every accuracy claim accordingly.** For roughly "
        f"{pct(n - rendered, n)} of this corpus, the benchmark measures "
        "*extraction from clean text*, not document extraction. Parse-stage failures — "
        "OCR error, layout collapse, table structure loss, glyph mis-decoding — are "
        "largely absent by construction.\n"
    )

    w("## By input tier\n")
    w("| Tier | Input | Real | Synthetic | Total | % of corpus |")
    w("|---|---|---:|---:|---:|---:|")
    for code, name, _ in TIERS:
        r_ = by_tier_prov[(code, "real")]
        s_ = by_tier_prov[(code, "synthetic")]
        if r_ + s_ == 0:
            continue
        w(f"| {code} | {name} | {r_} | {s_} | {r_ + s_} | {pct(r_ + s_, n)} |")
    w(f"| | **Total** | **{real}** | **{n - real}** | **{n}** | **100.0%** |\n")
    for code, name, desc in TIERS:
        if by_tier[code]:
            w(f"- **{code} — {name}.** {desc}")
    w("")

    w("## By category\n")
    w("| Category | n | Rendered page | HTML→md | Never a page |")
    w("|---|---:|---:|---:|---:|")
    cats = collections.defaultdict(list)
    for r in rows:
        cats[r["category"]].append(r)
    for cat in sorted(cats, key=lambda c: -len(cats[c])):
        cr = cats[cat]
        rp = sum(1 for r in cr if r["tier"] in RENDERED)
        html = sum(1 for r in cr if r["tier"] == "B")
        npg = sum(1 for r in cr if r["tier"] in ("C", "D"))
        off = sum(1 for r in cr if r["tier"] == "A3")
        rp_s = f"{rp + off}" + (f" ({off} office)" if off else "")
        w(f"| `{cat}` | {len(cr)} | {rp_s} | {html} | {npg} |")
    w("")

    w("## Why this matters for the real-vs-synthetic gap\n")
    w(
        "The corpus's headline finding compares *real* against *synthetic* documents. But "
        f"only {pct(real_rendered, real)} of the real documents came from a rendered page — "
        "the rest are clean EDGAR HTML or plain-text transcriptions. The real set is "
        "therefore *also* mostly clean input.\n"
    )
    w(
        "This means the measured real-vs-synthetic gap **understates** the true "
        "clean-vs-messy delta. A real-document set drawn from scans and layout-heavy PDFs "
        "would be expected to widen it, not narrow it. Report the gap as a lower bound.\n"
    )
    return "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("-o", "--output", type=pathlib.Path, help="write markdown here")
    ap.add_argument("--root", type=pathlib.Path, default=pathlib.Path("."))
    ap.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if --output is stale (for CI)",
    )
    args = ap.parse_args()

    rows = load(args.root)
    if not rows:
        print("error: no manifests found — run from the corpus root", file=sys.stderr)
        return 1
    md = render(rows)

    if args.check:
        if not args.output:
            print("error: --check requires --output", file=sys.stderr)
            return 1
        current = args.output.read_text() if args.output.exists() else ""
        if current != md:
            print(f"error: {args.output} is stale — regenerate it", file=sys.stderr)
            return 1
        print(f"{args.output} is up to date")
        return 0

    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(md)
        print(f"wrote {args.output} ({len(rows)} manifests)")
    else:
        sys.stdout.write(md)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
